# <font color="red"> MBA em IA e Big Data</font>
## <span style="color:red">Curso 2 - Ciência de Dados, Aprendizado de Máquina e Mineração de Dados</span>

### <span style="color:darkred">Mineração de Dados</span>

## Exercícios de Fixação - Aulas: Parte 6 até Parte 8

*Ricardo M. Marcacini*<br>
*ICMC/USP São Carlos*

#### <span style="color:red">Recomenda-se fortemente que os exercícios sejam feitos sem consultar as respostas antecipadamente.</span>

# Bibliotecas necessárias para execução dos exercícios

Nós usamos bibliotecas que geralmente estão disponíveis por padrão no ambiente Python-Anaconda e também no Google Colab. Caso receba mensagem de erro ao importar alguma das bibliotecas, então será necessário instalar o respectivo pacote no seu ambiente. Nesse caso, envie uma mensagem no fórum da disciplina para receber ajuda.

Para análise regras de associação, nós usaremos o pacote *mlxtend*.

O pacote já vem instalado no ambiente Google Colab. Em outros ambientes, pode ser necessário instalar com os comandos:

Opção 1: no terminal:

`pip install mlxtend`

Opção 2: no ambiente Jupyter/Notebook

`!pip install mlxtend`

Em alguns sistemas operacionais, como no Windows, pode ser necessário instalar bibliotecas adicionais, como a *openpyxl*. Nesse caso, o comando para instalar é:

`!pip install mlxtend openpyxl`


In [ ]:
# importando bibliotecas
import numpy as np
import pandas as pd
from sklearn import preprocessing
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.datasets import make_blobs

# Regras de Associação

Utilizar os dados do arquivo **grocery_store_transactions.csv** para realização dos Exercícios de Fixação sobre Regras de Associação.

Para executar o código abaixo, certifique-se de que o arquivo **grocery_store_transactions.csv** esteja no mesmo diretório desse script.

In [ ]:
transacoes = pd.read_csv('grocery_store_transactions.csv')
transacoes

BISCUIT  BOURNVITA  BREAD  COCK  COFFEE  ...  JAM  MAGGI  MILK  SUGER  TEA
0       1.0        0.0    1.0   0.0     0.0  ...  0.0    0.0   1.0    0.0  0.0
1       1.0        0.0    1.0   0.0     0.0  ...  0.0    0.0   1.0    0.0  0.0
2       0.0        1.0    1.0   0.0     0.0  ...  0.0    0.0   0.0    0.0  1.0
3       0.0        0.0    1.0   0.0     0.0  ...  1.0    1.0   1.0    0.0  0.0
4       1.0        0.0    0.0   0.0     0.0  ...  0.0    1.0   0.0    0.0  1.0
5       0.0        1.0    1.0   0.0     0.0  ...  0.0    0.0   0.0    0.0  1.0
6       0.0        0.0    0.0   0.0     0.0  ...  0.0    1.0   0.0    0.0  1.0
7       1.0        0.0    1.0   0.0     0.0  ...  0.0    1.0   0.0    0.0  1.0
8       0.0        0.0    1.0   0.0     0.0  ...  1.0    1.0   0.0    0.0  1.0
9       0.0        0.0    1.0   0.0     0.0  ...  0.0    0.0   1.0    0.0  0.0
10      1.0        0.0    0.0   1.0     1.0  ...  0.0    0.0   0.0    0.0  0.0
11      1.0        0.0    0.0   1.0     1.0  ...  0.0    0.0   0.0    0.0  0.0
12      0.0        1.0    0.0   0.0     1.0  ...  0.0    0.0   0.0    1.0  0.0
13      0.0        0.0    1.0   1.0     1.0  ...  0.0    0.0   0.0    0.0  0.0
14      1.0        0.0    1.0   0.0     0.0  ...  0.0    0.0   0.0    1.0  0.0
15      0.0        0.0    0.0   0.0     1.0  ...  0.0    0.0   0.0    1.0  0.0
16      0.0        1.0    1.0   0.0     0.0  ...  0.0    0.0   0.0    1.0  0.0
17      0.0        0.0    1.0   0.0     1.0  ...  0.0    0.0   0.0    1.0  0.0
18      0.0        0.0    1.0   0.0     1.0  ...  0.0    0.0   0.0    1.0  0.0
19      0.0        0.0    0.0   0.0     1.0  ...  0.0    0.0   1.0    0.0  1.0

[20 rows x 11 columns]

## Exercício 1

Obtenha os itemsets frequentes considerando um suporte mínimo (relativo) de 0.1 (10%)

In [ ]:
itemsets = apriori(transacoes, min_support = 0.1, use_colnames = True)
itemsets

support                             itemsets
0      0.35                            (BISCUIT)
1      0.20                          (BOURNVITA)
2      0.65                              (BREAD)
3      0.15                               (COCK)
4      0.40                             (COFFEE)
5      0.30                         (CORNFLAKES)
6      0.10                                (JAM)
7      0.25                              (MAGGI)
8      0.25                               (MILK)
9      0.30                              (SUGER)
10     0.35                                (TEA)
11     0.20                     (BISCUIT, BREAD)
12     0.10                      (COCK, BISCUIT)
13     0.10                    (BISCUIT, COFFEE)
14     0.15                (BISCUIT, CORNFLAKES)
15     0.10                     (MAGGI, BISCUIT)
16     0.10                      (BISCUIT, MILK)
17     0.10                       (TEA, BISCUIT)
18     0.15                   (BOURNVITA, BREAD)
19     0.10                   (SUGER, BOURNVITA)
20     0.10                     (TEA, BOURNVITA)
21     0.15                      (BREAD, COFFEE)
22     0.10                         (JAM, BREAD)
23     0.15                       (MAGGI, BREAD)
24     0.20                        (MILK, BREAD)
25     0.20                       (SUGER, BREAD)
26     0.20                         (TEA, BREAD)
27     0.15                       (COCK, COFFEE)
28     0.10                   (COCK, CORNFLAKES)
29     0.20                 (CORNFLAKES, COFFEE)
30     0.20                      (SUGER, COFFEE)
31     0.10                   (MILK, CORNFLAKES)
32     0.10                    (TEA, CORNFLAKES)
33     0.10                         (MAGGI, JAM)
34     0.20                         (MAGGI, TEA)
35     0.10               (BISCUIT, BREAD, MILK)
36     0.10              (COCK, BISCUIT, COFFEE)
37     0.10          (COCK, BISCUIT, CORNFLAKES)
38     0.10        (CORNFLAKES, BISCUIT, COFFEE)
39     0.10                (MAGGI, TEA, BISCUIT)
40     0.10              (TEA, BOURNVITA, BREAD)
41     0.10               (SUGER, BREAD, COFFEE)
42     0.10                  (MAGGI, JAM, BREAD)
43     0.10                  (MAGGI, TEA, BREAD)
44     0.10           (COCK, CORNFLAKES, COFFEE)
45     0.10  (COCK, CORNFLAKES, BISCUIT, COFFEE)

## Exercício 2

A partir dos itemsets frequentes obtidos no exercício anterior, gere as regras de associação considerando uma confiança mínima de 0.7 (70%)

In [ ]:
regras = association_rules(itemsets, metric = "confidence", min_threshold = 0.7)
regras

antecedents           consequents  ...  leverage  conviction
0                     (BOURNVITA)               (BREAD)  ...    0.0200        1.40
1                           (JAM)               (BREAD)  ...    0.0350         inf
2                          (MILK)               (BREAD)  ...    0.0375        1.75
3                          (COCK)              (COFFEE)  ...    0.0900         inf
4                           (JAM)               (MAGGI)  ...    0.0750         inf
5                         (MAGGI)                 (TEA)  ...    0.1125        3.25
6                 (BISCUIT, MILK)               (BREAD)  ...    0.0350         inf
7                 (COCK, BISCUIT)              (COFFEE)  ...    0.0600         inf
8               (BISCUIT, COFFEE)                (COCK)  ...    0.0850         inf
9                 (COCK, BISCUIT)          (CORNFLAKES)  ...    0.0700         inf
10             (COCK, CORNFLAKES)             (BISCUIT)  ...    0.0650         inf
11              (BISCUIT, COFFEE)          (CORNFLAKES)  ...    0.0700         inf
12               (MAGGI, BISCUIT)                 (TEA)  ...    0.0650         inf
13                 (TEA, BISCUIT)               (MAGGI)  ...    0.0750         inf
14               (TEA, BOURNVITA)               (BREAD)  ...    0.0350         inf
15                   (JAM, MAGGI)               (BREAD)  ...    0.0350         inf
16                   (JAM, BREAD)               (MAGGI)  ...    0.0750         inf
17                          (JAM)        (MAGGI, BREAD)  ...    0.0850         inf
18             (COCK, CORNFLAKES)              (COFFEE)  ...    0.0600         inf
19    (COCK, BISCUIT, CORNFLAKES)              (COFFEE)  ...    0.0600         inf
20     (COCK, COFFEE, CORNFLAKES)             (BISCUIT)  ...    0.0650         inf
21        (COCK, BISCUIT, COFFEE)          (CORNFLAKES)  ...    0.0700         inf
22  (COFFEE, BISCUIT, CORNFLAKES)                (COCK)  ...    0.0850         inf
23             (COCK, CORNFLAKES)     (BISCUIT, COFFEE)  ...    0.0900         inf
24                (COCK, BISCUIT)  (COFFEE, CORNFLAKES)  ...    0.0800         inf
25              (BISCUIT, COFFEE)    (COCK, CORNFLAKES)  ...    0.0900         inf

[26 rows x 9 columns]

## Exercício 3

A partir das regras de associação geradas no exercício anterior, selecione as top-3 regras mais interessantes conforme a medida objetiva LIFT.

In [ ]:
regras.sort_values(by=['lift'], ascending=False).head(3)

antecedents         consequents  ...  leverage  conviction
25   (BISCUIT, COFFEE)  (COCK, CORNFLAKES)  ...     0.090         inf
23  (COCK, CORNFLAKES)   (BISCUIT, COFFEE)  ...     0.090         inf
8    (BISCUIT, COFFEE)              (COCK)  ...     0.085         inf

[3 rows x 9 columns]

## Exercício 4

A partir das regras de associação geradas no Exercício 2, selecione as regras que possuem somente o item BREAD como consequente.


In [ ]:
regras[regras['consequents'] == {'BREAD'}]

antecedents consequents  ...  leverage  conviction
0        (BOURNVITA)     (BREAD)  ...    0.0200        1.40
1              (JAM)     (BREAD)  ...    0.0350         inf
2             (MILK)     (BREAD)  ...    0.0375        1.75
6    (BISCUIT, MILK)     (BREAD)  ...    0.0350         inf
14  (TEA, BOURNVITA)     (BREAD)  ...    0.0350         inf
15      (JAM, MAGGI)     (BREAD)  ...    0.0350         inf

[6 rows x 9 columns]

## Exercício 5

A partir das regras de associação geradas no Exercício 2, filtre todas as regras que possuem o suporte do antecedente igual ao suporte da regra. O que esse filtro significa em relação às medidas objetivas que estudamos?

**Resposta:**
*Significa que temos confiança máxima, uma vez que a confiança é sup(A U B)/sup(A). Consequentemente, temos convicção tendendo ao infinito.*

In [ ]:
regras[regras['antecedent support'] == regras['support']]

antecedents           consequents  ...  leverage  conviction
1                           (JAM)               (BREAD)  ...     0.035         inf
3                          (COCK)              (COFFEE)  ...     0.090         inf
4                           (JAM)               (MAGGI)  ...     0.075         inf
6                 (BISCUIT, MILK)               (BREAD)  ...     0.035         inf
7                 (COCK, BISCUIT)              (COFFEE)  ...     0.060         inf
8               (BISCUIT, COFFEE)                (COCK)  ...     0.085         inf
9                 (COCK, BISCUIT)          (CORNFLAKES)  ...     0.070         inf
10             (COCK, CORNFLAKES)             (BISCUIT)  ...     0.065         inf
11              (BISCUIT, COFFEE)          (CORNFLAKES)  ...     0.070         inf
12               (MAGGI, BISCUIT)                 (TEA)  ...     0.065         inf
13                 (TEA, BISCUIT)               (MAGGI)  ...     0.075         inf
14               (TEA, BOURNVITA)               (BREAD)  ...     0.035         inf
15                   (JAM, MAGGI)               (BREAD)  ...     0.035         inf
16                   (JAM, BREAD)               (MAGGI)  ...     0.075         inf
17                          (JAM)        (MAGGI, BREAD)  ...     0.085         inf
18             (COCK, CORNFLAKES)              (COFFEE)  ...     0.060         inf
19    (COCK, BISCUIT, CORNFLAKES)              (COFFEE)  ...     0.060         inf
20     (COCK, COFFEE, CORNFLAKES)             (BISCUIT)  ...     0.065         inf
21        (COCK, BISCUIT, COFFEE)          (CORNFLAKES)  ...     0.070         inf
22  (COFFEE, BISCUIT, CORNFLAKES)                (COCK)  ...     0.085         inf
23             (COCK, CORNFLAKES)     (BISCUIT, COFFEE)  ...     0.090         inf
24                (COCK, BISCUIT)  (COFFEE, CORNFLAKES)  ...     0.080         inf
25              (BISCUIT, COFFEE)    (COCK, CORNFLAKES)  ...     0.090         inf

[23 rows x 9 columns]

## Exercício 6

Tente gerar itemsets frequentes utilizando suporte=0.

O que acontece com o algoritmo APRIORI nesse cenário hipotético?

*Observação: se o método apriori não aceitar suporte=0 na sua versão do pacote mlxtend, então utilize um valor de suporte muito pequeno, como suporte=0.0000001 (nesse caso, o número de itemsets gerado será menor)*

**Resposta:**
*Nesse cenário hipotético, sem suporte mínimo, são geradas todas as possíveis combinações de itemsets, totalizando 2^d - 1, em que d é o total de items.*

In [ ]:
itemsets = apriori(transacoes, min_support = 0, use_colnames = True)
itemsets

support                                           itemsets
0        0.35                                          (BISCUIT)
1        0.20                                        (BOURNVITA)
2        0.65                                            (BREAD)
3        0.15                                             (COCK)
4        0.40                                           (COFFEE)
...       ...                                                ...
2042     0.00  (JAM, TEA, BOURNVITA, MAGGI, COFFEE, SUGER, BI...
2043     0.00  (JAM, TEA, BOURNVITA, MAGGI, COFFEE, SUGER, BI...
2044     0.00  (JAM, TEA, MAGGI, COFFEE, SUGER, BISCUIT, MILK...
2045     0.00  (JAM, TEA, BOURNVITA, MAGGI, COFFEE, SUGER, MI...
2046     0.00  (JAM, TEA, BOURNVITA, MAGGI, COFFEE, SUGER, BI...

[2047 rows x 2 columns]

# Classificação com k-NN

Para os exercícios 1 e 2 sobre classificação com k-NN, usaremos o conjunto de dados Wine. Algumas informações sobre o conjunto de dados são listadas a seguir.

In [ ]:
from sklearn.datasets import load_wine
data = load_wine()

Descrição do conjunto de dados

In [ ]:
print(data['DESCR'])

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

Separando os conjuntos de treinamento (70%) e teste (30%) para execução dos exercícios.

In [ ]:
X = data['data']
y = data.target
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3, random_state=42)

## Exercício 1

Utilize o kNN com k=3, distância euclidiana e voto majoritário nos dados do conjunto Wine. Não aplique nenhum tipo de pré-processamento nos dados. Use o método classification_report para obter algumas métricas de desempenho no conjunto de teste.

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3,metric="euclidean")
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89        19
           1       0.75      0.71      0.73        21
           2       0.53      0.57      0.55        14

    accuracy                           0.74        54
   macro avg       0.73      0.73      0.73        54
weighted avg       0.74      0.74      0.74        54



## Exercício 2

Repita o Exercício 1, mas agora aplicando o método MinMaxScaler para que todos os atributos tenham valores no intervalo [0,1]. Utilize os mesmos parâmetros do classificador kNN anterior. Apresente pelo menos um motivo para a diferença obtida nos resultados de classificação.

In [ ]:
min_max_scaler = preprocessing.MinMaxScaler()
min_max_scaler.fit(X_train)

X_train2 = min_max_scaler.transform(X_train)
X_test2 = min_max_scaler.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=3,metric="euclidean")
knn.fit(X_train2, y_train)
y_pred = knn.predict(X_test2)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97        19
           1       1.00      0.90      0.95        21
           2       0.93      1.00      0.97        14

    accuracy                           0.96        54
   macro avg       0.96      0.97      0.96        54
weighted avg       0.97      0.96      0.96        54



Atributos com maior variabilidade e com valores maiores podem "dominar" o valor da distância euclidiana. Por exemplo, os atributos "Magnesium" e "Proline" (ver descrição).

## Exercício 3

Considere o código abaixo que realiza classificação kNN em um conjunto (sintético) de dados com 100 mil objetos e 2 atributos. Realize uma segunda classificação kNN, mas usando uma kd-tree para particionar o espaço e acelerar os cálculos das distâncias. Compare o tempo de execução de cada classificação.

In [ ]:
X, y = make_blobs(n_samples=100000, centers=3, n_features=2, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
knn1 = KNeighborsClassifier(n_neighbors=3,algorithm='brute')
knn1.fit(X_train,y_train)

%time knn1.predict(X_test)

CPU times: user 13 s, sys: 1.79 s, total: 14.8 s
Wall time: 12.4 s


array([0, 2, 2, ..., 0, 1, 2])

In [ ]:
# com kd-tree
knn2 = KNeighborsClassifier(n_neighbors=3,algorithm='kd_tree')
knn2.fit(X_train,y_train)

%time knn2.predict(X_test)

CPU times: user 315 ms, sys: 2.21 ms, total: 317 ms
Wall time: 315 ms


array([0, 2, 2, ..., 0, 1, 2])

## Exercício 4

Considere o código abaixo que realiza classificação kNN em um conjunto (sintético) de dados com 50 mil objetos e 30 atributos. Repita a operação anterior visando uma classificação kNN com uma kd-tree para particionar o espaço. Compare o tempo de execução de cada classificação. Por qual motivo o desempenho da kd-tree foi menor nesse caso?

In [ ]:
X, y = make_blobs(n_samples=50000, centers=3, n_features=30, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
knn1 = KNeighborsClassifier(n_neighbors=3,algorithm='brute')
knn1.fit(X_train,y_train)

%time knn1.predict(X_test)

CPU times: user 3.74 s, sys: 270 ms, total: 4.01 s
Wall time: 3.22 s


array([2, 0, 0, ..., 2, 2, 0])

In [ ]:
# com kd-tree
knn2 = KNeighborsClassifier(n_neighbors=3,algorithm='kd_tree')
knn2.fit(X_train,y_train)

%time knn2.predict(X_test)

CPU times: user 8.76 s, sys: 3.27 ms, total: 8.76 s
Wall time: 8.73 s


array([2, 0, 0, ..., 2, 2, 0])

Quando kd-tree é usada com dados de alta dimensão, seu desempenho para particionar o espaço é reduzido. Nesse cenário, seu desempenho não é melhor do que uma pesquisa exaustiva.